---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: traefik
  name: codeserver-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /codeserver
    forceSlash: true
