---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: unifi-poller-kustomization

resources:
  - deployment.yaml
  - podmonitor.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"

configMapGenerator:
  - name: unpollerdashboard-network-sites-11311
    files: [ unpollerdashboard-network-sites-11311.json ]

  - name: unpollerdashboard-usw-insights-11312
    files: [ unpollerdashboard-usw-insights-11312.json ]
    
  - name: unpollerdashboard-uap-insights-11314
    files: [ unpollerdashboard-uap-insights-11314.json ]

  - name: unpollerdashboard-client-insights-11314
    files: [ unpollerdashboard-client-insights-11315.json ]
