{
 "title": "Mosquitto broker",
 "description": "Supports https://github.com/sapcc/mosquitto-exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "broker_uptime" }
   ]
  },
  {
   "title": "Subscription count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "broker_subscriptions_count" }
   ]
  },
  {
   "title": "Clients connected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "broker_clients_connected" }
   ]
  },
  {
   "title": "Transfered data sum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "broker_bytes_received + broker_bytes_sent"
    }
   ]
  },
  {
   "title": "Published messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(broker_publish_messages_sent[$__interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(broker_publish_messages_received[$__interval])*-1",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Transfered data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(broker_bytes_sent[$__interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(broker_bytes_received[$__interval])*-1",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}