---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: unifi-poller-kustomization

bases:
  - ./base/application/

images:
  - name: golift/unifi-poller
    newTag: 2.1.3

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: unpoller-config-file
    files:
      - ./base/conf/up.conf

# Create a Read-Only Unifi Console Admin, enter credentials below
# Don't base64 encode secret values here
#secretGenerator:
#- name: unpoller-secret
#  literals:
#  - unifi-user=<USERNAME_HERE>
#  - unifi-pass=<PASSWORD_HERE>

# Patched below set the namespace where Prometheus is located and 
# set the release label Prometheus uses for PodMonitor auto-discovery
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
    target:
      kind: PodMonitor

  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
      - op: add
        path: /metadata/labels/grafana_dashboard
        value: "true"
    target:
      kind: ConfigMap
      name: unpollerdashboard-.*
  
commonLabels:
  app: unpoller
  app.kubernetes.io/instance: unpoller
  app.kubernetes.io/name: unpoller