---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./base/application/

images:
  - name: golift/unifi-poller
    newTag: 2.1.3

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: unpoller-config-file
    files:
      - ./base/conf/up.conf

# Create a Read-Only Unifi Console Admin, enter credentials below
# Don't base64 encode secret values here
#secretGenerator:
#- name: unpoller-secret
#  literals:
#  - unifi-user=<USERNAME_HERE>
#  - unifi-pass=<PASSWORD_HERE>

# Set namespace where Prometheus is located
# Set label Prometheus uses for PodMonitor auto-discovery
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
      - op: replace
        path: /metadata/labels/release
        value: kube-prometheus-stack
    target:
      kind: PodMonitor

  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: monitoring
    target:
      kind: ConfigMap
      name: unpollerdashboard-*
  
commonLabels:
  app: unpoller
  app.kubernetes.io/instance: unpoller
  app.kubernetes.io/name: unpoller