---
# Setup non-root user for interacting with Kubernetes.

- name: Create non-Root User Block
  block:

  - name: Add non-root user that will be used with Kubernetes
    ansible.builtin.user:
      name: "{{install.os.non_root_user.name}}"
      shell: "{{install.os.non_root_user.shell}}"
      groups: "{{install.os.non_root_user.groups}}"
      append: yes
      createhome: yes

  - name: Allow non-root user to have passwordless sudo convenience
    ansible.builtin.lineinfile:
      dest: /etc/sudoers
      line: "{{install.os.non_root_user.name}} ALL=(ALL) NOPASSWD: /usr/local/bin/kubectl"
      validate: "visudo -cf %s"
    when:
      - install.os.allow_passwordless_sudo|default(false)|bool == true

  tags:
    - create_non_root_user