---
# [ Apply Node Labels ]############################################################################
- name: Apply Node Labels
  when:
    - k3s_labels is defined
  tags:
    - apply_labels
  block:
    # Worker / Agents do not have permission to added labels directly
    # task is delegated to control-plane node to execute
    - name: Apply any defined node labels, delegate to control-plane node
      ansible.builtin.command:
        argv:
          - /usr/local/bin/kubectl
          - label
          - --overwrite
          - node
          - "{{ inventory_hostname_short }}"
          - "{{ item }}"
      register: cmd
      changed_when: cmd.rc == 0
      with_items:
        - "{{ k3s_labels }}"
      delegate_facts: true
      delegate_to: "{{ groups['k3s_control'][0] }}"
