---
# Install MetalLB Load Balancer

- name: Install MetalLB Load Balancer Block
  block:

  - name: Create Directory for MetalLB Configuration
    file:
      path: "/home/{{install.os.non_root_user.name}}/metal_lb"
      state: directory
      mode: 0750
      owner: "{{install.os.non_root_user.name}}"
      group: "{{install.os.non_root_user.name}}"

  - name: Fetch Static Manifest to Install Metallb
    ansible.builtin.get_url:
      url: "{{metallb.install_url}}/{{item}}"
      dest: "/home/{{install.os.non_root_user.name}}/metal_lb/{{item}}-{{install.metallb.install_version}}-manifest.yaml"
      mode: '0664'
      owner: "{{install.os.non_root_user.name}}"
      group: "{{install.os.non_root_user.name}}"
    loop: "{{metallb.install_manifests}}"
    loop_control:
      label: "{{item}}"

  - name: Copy MetalLB Template Files
    template:
     src: "templates/metallb/{{item}}.j2"
     dest: "/home/{{install.os.non_root_user.name}}/metal_lb/{{item}}"
     owner: "{{install.os.non_root_user.name}}"
     group: "{{install.os.non_root_user.name}}"
     mode: '0660'
    loop:
      - configmap.yaml
    loop_control:
      label: "{{item}}"

  - name: Install MetalLB via static Manifest
    kubernetes.core.k8s:
      state: present
      src: "/home/{{install.os.non_root_user.name}}/metal_lb/{{item}}-{{install.metallb.install_version}}-manifest.yaml"
    loop: "{{metallb.install_manifests}}"
    loop_control:
      label: "{{item}}"

  - name: Install MetalLB ConfigMap
    kubernetes.core.k8s:
      state: present
      src: "/home/{{install.os.non_root_user.name}}/metal_lb/configmap.yaml"

  - name: Check Controller Pod is Running
    k8s_info:
      kind: Pod
      namespace: "metallb-system"
      label_selectors:
        - "app=metallb"
        - "component=controller"
      wait: yes
      wait_condition:
        type: Ready
      wait_sleep: 5
      wait_timeout: 120

  when:
    - install.metallb.enabled|default(false)|bool == true
  tags:
    - install_metallb
