---
#
# Deploy additional applications based on if enabled.
#

###[ Deploy Additional Applications ]##############################################################
- name: Process Applications to Deploy Block
  block:
  - name: Clone Remote ArgoCD Repository
    ansible.builtin.git:
      repo: "{{install.argocd.repository.url|urlsplit('scheme')}}://{{install.argocd.repository.username}}:{{install.argocd.repository.password}}@{{install.argocd.repository.url|urlsplit('hostname')}}{{install.argocd.repository.url|urlsplit('path')}}"
      dest: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
      force: yes

  # Applications templates to render and then check into Git repository are defined below
  # Only process templates if application is enabled.
  - name: Process Deployable Enabled Applications
    include_tasks: "process_app_to_deploy.yml"
    loop:
      - { enabled: "{{install.kube_vip.enabled|default(false)|bool}}",    name: "kube-vip" }
      - { enabled: "{{install.kube_vip.lb.enabled|default(false)|bool}}", name: "kube-vip-cloud-provider" }
    when:
      - deploy_app.enabled == true
    loop_control:
      loop_var: deploy_app
      label: "{{deploy_app}}"

  - name: Check-in Any New or Modified Files
    include_tasks: "checkin_argocd_repo_files.yml"

  when: 
    - inventory_hostname == groups['k3s_control'][0]
    - install.argocd.enabled|default(false)|bool == true
  tags:
    - deploy_apps

# Make sure all changes are checked in before removing repository
- name: Flush Handlers
  meta: flush_handlers
  tags:
    - deploy_apps

# Probably not safe to leave these on the K3s instance
- name: Delete Local ArgoCD Secrets and Git Repo
  ansible.builtin.file:
    path: "/home/{{install.os.non_root_user.name}}/argocd"
    state: absent
  when: 
    - inventory_hostname == groups['k3s_control'][0]
    - install.argocd.enabled|default(false)|bool == true
  tags:
    - deploy_apps
