---
#
# Add iSCSI persistent storage with TrueNas integration via democratic-csi packages.
#
# based on: https://jonathangazeley.com/2021/01/05/using-truenas-to-provide-persistent-storage-for-kubernetes/

###[ Install democratic-csi packages ]############################################################
- name: Install democratic-csi Repository via Helm Block
  block:
  - name: Install iSCSI Support packages
    apt:
      name: "{{install.democratic_csi.iscsi.packages}}"
      state: present

  - name: Copy multipath.Conf File
    copy:
      src: "files/multipath.conf"
      dest: "/etc/multipath.conf"

  - name: Add democratic-csi Repository to Helm
    kubernetes.core.helm_repository:
      name: democratic-csi
      repo_url: "{{democratic_csi.repo_url}}"

  - name: Enable and Start multipath-tools Service
    ansible.builtin.systemd:
      enabled: yes
      state: restarted
      name: multipath-tools

  - name: Enable and Start open-iscsi Service
    ansible.builtin.systemd:
      enabled: yes
      state: restarted
      name: open-iscsi

  - name: Create directory for democratic-csi yaml files for non-root user
    file:
      path: "/home/{{install.os.non_root_user.name}}/democratic-csi"
      state: directory
      mode: 0700
      owner: "{{install.os.non_root_user.name}}"
      group: "{{install.os.non_root_user.name}}"

  - name: Copy democratic-csi Template Files
    template:
      src: "templates/democratic_csi/{{item}}.j2"
      dest: "/home/{{install.os.non_root_user.name}}/democratic-csi/{{item}}"
      owner: "{{install.os.non_root_user.name}}"
      group: "{{install.os.non_root_user.name}}"
      mode: '0660'
    loop:
      - "test-claim-iscsi.yaml"

  - name: "Copy and Validate iSCSI Provisioner - {{install.democratic_csi.iscsi.provisioner}}.yaml"
    template:
      src: "templates/democratic_csi/{{install.democratic_csi.iscsi.provisioner}}.yaml.j2"
      dest: "/home/{{install.os.non_root_user.name}}/democratic-csi/{{install.democratic_csi.iscsi.provisioner}}.yaml"
      owner: "{{install.os.non_root_user.name}}"
      group: "{{install.os.non_root_user.name}}"
      mode: '0660'
      validate: "helm upgrade --dry-run --install --create-namespace --values %s --namespace {{install.democratic_csi.iscsi.namespace}} {{install.democratic_csi.iscsi.release}} {{democratic_csi.repo_chart_ref}}"
      backup: yes

  - name: Install democratic-csi iSCSI Provisioner via Helm
    kubernetes.core.helm:
      update_repo_cache: yes
      atomic: yes
      create_namespace: yes
      chart_ref: "{{democratic_csi.repo_chart_ref}}"
      chart_version: "{{install.democratic_csi.install_version}}"
      release_name: "{{install.democratic_csi.iscsi.release}}"
      release_namespace: "{{install.democratic_csi.iscsi.namespace}}"
      release_state: present
      values_files: "/home/{{install.os.non_root_user.name}}/democratic-csi/{{install.democratic_csi.iscsi.provisioner}}.yaml"
      wait: yes
      wait_timeout: 5m

  tags:
    - install_democratic_csi_iscsi
  when:
    - install.democratic_csi.iscsi.provisioner is defined
    - install.democratic_csi.iscsi.install_this|default(false)|bool == true