---
#
# Configure Kubernetes Traefik Ingress Controller
#

- name: Setup Kubernetes Traefik Ingress Controller Environment Block
  block:

  - name: Create directory for Traefik yaml files for non-root user
    file:
      path: "/home/{{install.os.non_root_user.name}}/traefik"
      state: directory
      mode: 0700
      owner: "{{install.os.non_root_user.name}}"
      group: "{{install.os.non_root_user.name}}"

  tags:
   - config_traefik_dns_certs
   - config_traefik_dashboard

###[ Uses Cloudflare DNS Challenge ]###############################################################
# Based on: https://it-obey.com/index.php/wildcard-certificates-dns-challenges-and-traefik-in-kubernetes/

- name: Configure Kubernetes Traefik LetsEncrypt for Cloudflare DNS Challenge Block
  block:
  - name: Copy Traefik Template Files
    template:
     src: "templates/traefik/{{item}}.j2"
     dest: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     owner: "{{install.os.non_root_user.name}}"
     group: "{{install.os.non_root_user.name}}"
     mode: '0660'
    loop:
      - cloudflare_api_token_secret.yaml
      - letsencrypt_wildcard_cert.yaml
      - letsencrypt.yaml
      - traefik_default_tls_store.yaml
      - traefik_test_apps.yaml

  - name: Apply Traefik Certificates Scripts
    kubernetes.core.k8s:
     state: present
     src: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     wait: yes
     wait_timeout: 300
    with_items:
      - cloudflare_api_token_secret.yaml
      - letsencrypt_wildcard_cert.yaml
      - letsencrypt.yaml
      - traefik_default_tls_store.yaml
  when:
    - inventory_hostname == groups['k3s_control'][0]
  
  tags:
   - config_traefik_dns_certs

###[ Configure Traefik Dashboard ]#################################################################
- name: Configure Kubernetes Traefik Dashboard Block
  block:
  - name: Copy Traefik Template Files
    template:
     src: "templates/traefik/{{item}}.j2"
     dest: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     owner: "{{install.os.non_root_user.name}}"
     group: "{{install.os.non_root_user.name}}"
     mode: '0660'
    loop:
      - traefik_dashboard.yaml
  
  - name: Apply Traefik Dashboard Scripts
    kubernetes.core.k8s:
     state: present
     src: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     wait: yes
     wait_timeout: 300
    with_items:
      - traefik_dashboard.yaml
    when:
      - install.traefik.dashboard.create_route|default(false) == true

  - name: Apply Traefik Dashboard Scripts
    kubernetes.core.k8s:
     state: absent
     src: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     wait: yes
     wait_timeout: 300
    with_items:
      - traefik_dashboard.yaml
    when:
      - install.traefik.dashboard.create_route|default(false) == false

  when:
    - inventory_hostname == groups['k3s_control'][0]
    
  tags:
   - config_traefik_dashboard
