---
#
# Configure Traefik Ingress Controller
#

- name: Configure Traefik Ingress Controller Block
  block:
  - name: Copy Traefik Template Files
    template:
     src: "templates/traefik/{{item}}.j2"
     dest: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     owner: "{{install.os.non_root_user.name}}"
     group: "{{install.os.non_root_user.name}}"
     mode: '0660'
    loop:
      - traefik_wildcard_cert.yaml
      - traefik_default_tls_store.yaml
      - traefik_test_apps.yaml
      - traefik_dashboard.yaml

  - name: Apply Traefik Template Scripts
    kubernetes.core.k8s:
     state: present
     src: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     wait: yes
     wait_timeout: 300
    with_items:
      - traefik_wildcard_cert.yaml
      - traefik_default_tls_store.yaml
  
  - name: Apply Traefik Dashboard Scripts
    kubernetes.core.k8s:
     state: present
     src: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     wait: yes
     wait_timeout: 300
    with_items:
      - traefik_dashboard.yaml
    when:
      - install.traefik.dashboard.create_route|default(false) == true

  - name: Apply Traefik Dashboard Scripts
    kubernetes.core.k8s:
     state: absent
     src: "/home/{{install.os.non_root_user.name}}/traefik/{{item}}"
     wait: yes
     wait_timeout: 300
    with_items:
      - traefik_dashboard.yaml
    when:
      - install.traefik.dashboard.create_route|default(false) == false

  when:
    - inventory_hostname == groups['k3s_control'][0]
  tags:
   - config_traefik
