---
#
# Validate the democratic-csi iSCSI installation is running as expected.
#

###[ Validate democratic-csi iSCSI Kubernetes Installation ]#######################################
- name: Validate democratic-csi iSCSI Kubernetes Installation Block
  block:
  - name: Check Pods are Running (multiple types are expected)
    k8s_info:
      kind: Pod
      namespace: "{{install.democratic_csi.iscsi.namespace}}"
      field_selectors:
        - "status.phase=Running"
    register: csi_pods_details

  # Set Fact if we can detect the controller pod running
  - set_fact:
      csi_controller_running: true
    loop: "{{csi_pods_details.resources}}"
    when: item.metadata.labels['app.kubernetes.io/csi-role'] == "controller"

  # Set Fact if we can detect the node pod running
  - set_fact:
      csi_node_running: true
    loop: "{{csi_pods_details.resources}}"
    when: item.metadata.labels['app.kubernetes.io/csi-role'] == "node"

  - name: Fail if democratic-csi controller pod not running
    fail:
      msg: |
        Unable to detect democratic-csi controller pod is running. Check this...
        
        kubectl get pods -n {{install.democratic_csi.iscsi.namespace}} -o wide
    when: csi_controller_running is not defined

  - name: Fail if democratic-csi node pod not running
    fail:
      msg: "Unable to detect democratic-csi node pod is running"
    when: csi_node_running is not defined

  - name: "Check if iSCSI Storageclass is created"
    k8s_info:
      kind: StorageClass
      namespace: "{{install.democratic_csi.iscsi.namespace}}"
      field_selectors:
        - "metadata.name={{install.democratic_csi.iscsi.provisioner}}-csi"
    register: csi_storageclass_details

  # Set Fact if we can detect the storage class
  - set_fact:
      csi_storage_class: true
    loop: "{{csi_storageclass_details.resources}}"
    when: item.provisioner == "org.democratic-csi.iscsi"

  - name: Fail if democratic-csi iSCSI storage class not detected
    fail:
      msg: |
        Unable to detect democratic-csi iSCSI storage class, try:
        
        kubectl get sc -n {{install.democratic_csi.iscsi.namespace}}
    when: csi_storage_class is not defined

  ###[ Perform iSCSI Test Claim and Validate Block ]###############################################
  - name: Perform iSCSI Test Claim and Validate Block
    block:
    - name: Perform iSCSI test claim
      kubernetes.core.k8s:
        src: "/home/{{install.os.non_root_user.name}}/democratic-csi/test-claim-iscsi.yaml"
        state: present
        namespace: "{{install.democratic_csi.iscsi.namespace}}"
        wait: yes
        wait_timeout: 120

    - name: Pause for 5 seconds for iSCSI claim provision to process
      wait_for:
        timeout: 5

    - name: "Check if iSCSI test claim is created"
      k8s_info:
        kind: PersistentVolumeClaim
        namespace: "{{install.democratic_csi.iscsi.namespace}}"
        field_selectors:
          - "metadata.name=test-claim-iscsi"
      register: csi_iscsi_storage_claim_details

    # Set Fact if we can detect storage claim phase "Bound"
    - set_fact:
        csi_iscsi_storage_claim: true
      loop: "{{csi_iscsi_storage_claim_details.resources}}"
      when: item.status.phase == "Bound"

    - name: Fail if democratic-csi iSCSI storage claim not detected
      fail:
        msg: |
          Unable to detect democratic-csi iSCSI storage claim, try:
          
          kubectl get pvc -n {{install.democratic_csi.iscsi.namespace}}
      when: csi_iscsi_storage_claim is not defined

    - name: Remove iSCSI test claim - validations passed
      kubernetes.core.k8s:
        src: "/home/{{install.os.non_root_user.name}}/democratic-csi/test-claim-iscsi.yaml"
        state: absent
        namespace: "{{install.democratic_csi.iscsi.namespace}}"
        wait: yes
        wait_timeout: 120

    when: install.democratic_csi.iscsi.test_claim.enabled|default(false)|bool == true

  tags:
    - validate_csi_iscsi
  when:
    - install.democratic_csi.iscsi.provisioner is defined
    - install.democratic_csi.iscsi.install_this|default(false)|bool == true
