---
#
# Validate the democratic-csi NFS installation is running as expected.
#

###[ Validate democratic-csi NFS Kubernetes Installation ]#########################################
- name: Validate democratic-csi NFS Kubernetes Installation Block
  block:
  - name: Check Pods are Running (multiple types are expected)
    k8s_info:
      kind: Pod
      namespace: "{{install.democratic_csi.nfs.namespace}}"
      field_selectors:
        - "status.phase=Running"
    register: csi_pods_details

  # Set Fact if we can detect the controller pod running
  - set_fact:
      csi_controller_running: true
    loop: "{{csi_pods_details.resources}}"
    when: item.metadata.labels['app.kubernetes.io/csi-role'] == "controller"

  # Set Fact if we can detect the node pod running
  - set_fact:
      csi_node_running: true
    loop: "{{csi_pods_details.resources}}"
    when: item.metadata.labels['app.kubernetes.io/csi-role'] == "node"

  - name: Fail if democratic-csi controller pod not running
    fail:
      msg: |
        Unable to detect democratic-csi controller pod is running, try:
        
        kubectl get pods -n {{install.democratic_csi.nfs.namespace}} -o wide
    when: csi_controller_running is not defined

  - name: Fail if democratic-csi node pod not running
    fail:
      msg: "Unable to detect democratic-csi node pod is running"
    when: csi_node_running is not defined

  # if this failed check "kubectl get sc -A"
  - name: "Check if NFS Storage class is created"
    k8s_info:
      kind: StorageClass
      namespace: "{{install.democratic_csi.nfs.namespace}}"
      field_selectors:
        - "metadata.name={{install.democratic_csi.nfs.provisioner}}-csi"
    register: csi_storageclass_details
    until: csi_storageclass_details.resources[0].provisioner == "org.democratic-csi.nfs"
    retries: 4
    delay: 5

  ###[ Perform NFS Test Claim and Validate Block ]#################################################
  - name: Perform NFS Test Claim and Validate Block
    block:
    - name: Perform NFS test claim
      kubernetes.core.k8s:
        src: "/home/{{install.os.non_root_user.name}}/democratic-csi/test-claim-nfs.yaml"
        state: present
        namespace: "{{install.democratic_csi.nfs.namespace}}"
        wait: yes
        wait_timeout: 120

    - name: "Check if NFS test claim is created"
      k8s_info:
        kind: PersistentVolumeClaim
        namespace: "{{install.democratic_csi.nfs.namespace}}"
        field_selectors:
          - "metadata.name=test-claim-nfs"
      register: csi_nfs_storage_claim_details
      until: csi_nfs_storage_claim_details.resources[0].status.phase == "Bound"
      retries: 5
      delay: 10

    - name: Remove NFS test claim - validations passed
      kubernetes.core.k8s:
        src: "/home/{{install.os.non_root_user.name}}/democratic-csi/test-claim-nfs.yaml"
        state: absent
        namespace: "{{install.democratic_csi.nfs.namespace}}"
        wait: yes
        wait_timeout: 120

    when: install.democratic_csi.nfs.test_claim.enabled|default(false)|bool == true

  tags:
    - validate_csi_nfs
  when:
    - install.democratic_csi.nfs.provisioner is defined
    - install.democratic_csi.nfs.install_this|default(false)|bool == true