---

- name: Check if any ArgoCD Repository Files were Updated
  ansible.builtin.command:
    chdir: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
    argv:
      - /usr/bin/git
      - status
  register: git_status

- name: Git Checkin and Commit Block
  block:
  - name: Add New Files Generated Files to ArgoCD Repository
    ansible.builtin.command:
      chdir: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
      argv:
        - /usr/bin/git
        - add
        - --all
    register: git_add

  - name: Commit Checked in Files to ArgoCD Repository
    ansible.builtin.command:
      chdir: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
      argv:
        - /usr/bin/git
        - commit
        - -a
        - -m
        - "Commit via Ansible {{commit_message|default('')}}"

  - name: Git Push ArgoCD
    ansible.builtin.command:
      chdir: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
      argv:
        - /usr/bin/git
        - push

  when:
    - '("nothing to commit" not in git_status.stdout) or ("Untracked files" in git_status.stdout)' 
