---
####################################################################################################
# This script is for installing k3s distribution of Kubernetes. k3s does not have native support
# for ZFS file system (will produce overlayfs errors).  
# See: https://github.com/k3s-io/k3s/discussions/3980
#
# This script by default will also install containerd and container network plugins packages which
# is configured to support ZFS.  Then k3s configuration will be updated to use containerd.
# Based on: https://blog.nobugware.com/post/2019/k3s-containterd-zfs/

###[ Load up the secret files ]####################################################################
#- name: Include Secret Files
#  include_vars: "{{ item }}"
#  tags: ["always"]
#  loop:
    #- secrets/letsencrypt_secrets.yml
    #- secrets/k3s_traefik_api_secrets.yml
    #- secrets/truenas_api_secrets.yml
    #- secrets/longhorn_dashboard_secrets.yml
    #- secrets/prometheus_dashboard_secrets.yml
    #- secrets/alertmanager_dashboard_secrets.yml
    #- secrets/alertmanager_secrets.yml
#  no_log: "{{no_log_secrets|default(true)}}"

###[ Detect ZFS UUID from ZFS on Root installations ]##############################################
- name: Detect ZFS Dataset UUID
  shell:
    cmd: "{{containerd.zfs.zfs_uuid_detect_cmd}}"
  register: UUID
  tags: ["always"]
  when:
    - install.containerd.zfs.detect_uuid|default(false)|bool == true
###################################################################################################

- name: Include Task Files
  include_tasks: "{{task_names}}"
  tags: ["always"]
  loop:
    - 00_sanity_check.yml
    - 00_config_rsyslog.yml
    - 00_prep_os.yml
    - 01_install_k3s.yml
    - 02_install_containerd.yml
    - 03_apply_labels.yml
    - 04_validate_k3s.yml
    - 05_install_helm_client.yml

  loop_control:
    label: "{{task_names}}"
    loop_var: task_names
