---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./base/application/

# Set namespace where Prometheus is located
# Set label Prometheus uses for PrometheusRule auto-discovery
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: monitoring
  target:
    kind: PrometheusRule