apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  template:
    spec:
      containers:
        - name: gitea
          resources: {}
          # resources:
          #   requests:
          #      cpu: "15m"
          #      memory: "175Mi"
          #    limits:
          #      cpu: "75m"
          #      memory: "512Mi"