---
install:
  ###[ Linux OS Configuration ]####################################################################
  os:
    non_root_user:
      name: "kube"
      shell: "/bin/bash"
      groups: "sudo"

    allow_passwordless_sudo: true

  ###[ Domain Names for LetsEncrypt Certificates ]#################################################
  domains:
    - "rich-durso.us"
    - "*.rich-durso.us"

  k3s:
    # Packages required for Ansible to issue Kubernetes and commands
    packages:
      - python3-pip
    packages_pip:
      - openshift
      - pyyaml
      - kubernetes

    # CLI options passed directly to install script "as-is":
    cli_options:
      # Do not start service after installation as it will have issues with ZFS
      - INSTALL_K3S_SKIP_START=true
      # This is to pin a specific version of k3s for initial installation
      # - INSTALL_K3S_VERSION=
      # Select installation channel to use (stable, latest, testing)
      - INSTALL_K3S_CHANNEL="latest"
      # Send Flags to K3s Service
      - INSTALL_K3S_EXEC="--container-runtime-endpoint unix:///run/containerd/containerd.sock"

    url: "https://get.k3s.io"

    # If enabled, will fail ansible deployment when "kubectl get node" returns "No resources found"
    confirm_running: true
  
  ###[ Containerd Installation Settings ]##########################################################
  containerd:
    packages:
      - containerd
      - containernetworking-plugins
      - iptables
    
    # Location generate config.toml file
    config_path: "/etc/containerd"

    # Location to place flannel.conflist
    flannel_conflist_path: "/etc/cni/net.d"

    # Hint to find the ZFS pool & dataset to create containerd mount point
    zfs:
      # detect_uuid will determine the UUID name used for the dataset name and include it.
      # ZFS on Root guide uses a random set of characters (UUID) in the naming convention
      # such as:  "rpool/ROOT/ubuntu_3wgs2q" where "3wgs2q" is the UUID to detect.
      
      # You can set to false and set your own or set uuid to empty string.

      # End result would be a dataset name such as:  rpool/ROOT/ubuntu_3wgs2q/var/lib/containerd
      detect_uuid: false
      pool: "rpool"
      dataset_prefix: "containerd"            # "ROOT/ubuntu"
      uuid: ""                                # "_"
      dataset_postfix: ""                     # "/var/lib/containerd"
  
  ###[ Cert Manager Installation Settings ]########################################################
  cert_manager:
    # Select release to use:  https://github.com/cert-manager/cert-manager/releases
    install_version: "v1.7.1"

  ###[ Democratric CSI Installation Settings ]#####################################################
  democratic_csi:
    # Available: https://github.com/democratic-csi/democratic-csi/tree/master/examples
    iscsi:
      provisioner: "freenas-iscsi"

      packages:
        - open-iscsi
        - lsscsi
        - sg3-utils
        - multipath-tools
        - scsitools

      truenas:
        # See file "truenas_api_secrets.yml" to set secrets (and be sure to use ansible vault to encrypt!)
        http_connection:
          protocol: "https"
          port: 443
          allow_insecure: false
          host: "{{democratic_csi.http_hostname}}"
          api_key: "{{democratic_csi.http_api_key}}"

        ssh_connection:
          host: "{{democratic_csi.ssh_hostname}}"
          port: 22
          user: "{{democratic_csi.ssh_username}}"
          
          # Must use a password or private key
          #password: "{{democratic_csi.ssh_password}}"
          private_key: "{{democratic_csi.ssh_private_key}}"

        zfs:
          fs_type: "xfs"   # zvol block-based storage can be formatted as ext3, ext4, xfs
          
          # Assumes pool named "main", dataset named "k8s", child dataset "iscsi"
          # Any additional provisioners such as NFS would be at the same level as "iscsi" (sibling of it)
          # IMPORTANT:
          #   total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
          #   https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
          #   standard volume naming overhead is 46 chars
          #   Which means names **MUST-BE** 17 characters or LESS!!!!
          dataset:
            parent_name: "main/k8s/iscsi/v"
            snapshot_ds_name: "main/k8s/iscsi/s"

            zvol_compression: "lz4"     # "" (inherit), lz4, gzip-9, etc
            zvol_Blocksize: ""          # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
          
        iscsi:
          host: "{{democratic_csi.iscsi_hostname}}"
          port: 3260
          
          #interface: ""                 # leave empty to omit usage of -I with iscsiadm
          name_prefix: csi-
          name_suffix: "-clustera"
          
          target_group:
            portal_group: 1             # get the correct ID from the "portal" section in the UI
            initiator_group: 1          # get the correct ID from the "initiators" section in the UI
            auth_type: "None"           # None, CHAP, or CHAP Mutual

            # get the correct ID from the "Authorized Access" section of the UI
            auth_group: ""              # only required if using CHAP
          
          extent:
            block_size: 4096            # 512, 1024, 2048, or 4096
            rpm: "5400"                 # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
            avail_threshold: 0          # 0-100 (0 == ignore)
      
          

