---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: {{install.argocd.namespace}}
  name: applications
spec:
  project: default

  source:
    repoURL: {{install.argocd.repository.url}}.git
    targetRevision: HEAD
    path: applications/
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: {{install.argocd.namespace}}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    -  Validate=true