---
- name: Restart Containerd Service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    name: containerd

- name: Restart k3s Service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    name: k3s

- name: Restart rsyslog service
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    name: rsyslog

- name: Commit Checked in Files to ArgoCD Repository
  ansible.builtin.command:
    chdir: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
    argv:
      - /usr/bin/git
      - commit
      - -a
      - -m
      - "Commit via Ansible"
  notify:
    - Git Push ArgoCD

- name: Git Push ArgoCD
  ansible.builtin.command:
   chdir: "/home/{{install.os.non_root_user.name}}/argocd/init_git_repo/"
   argv:
     - /usr/bin/git
     - push
