# References:
# https://github.com/rook/rook/tree/master/Documentation/Helm-Charts
# https://github.com/rook/rook/blob/master/Documentation/Helm-Charts/operator-chart.md

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: rook-ceph-operator
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"  # Lower the number the sooner to deploy
spec:
  project: storage
  revisionHistoryLimit: 3
  
  source:
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.10.6
    helm:
      # https://github.com/rook/rook/blob/master/deploy/charts/rook-ceph/values.yaml
      values: |
          ## Whether the helm chart should create and update the CRDs.
          crds:
            enabled: true

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 120m
              memory: 150Mi

          ## The logging level for the operator: ERROR | WARNING | INFO | DEBUG
          logLevel: INFO

          ## If true, create & use RBAC resources
          rbacEnable: true

          ## If true, create & use PSP resources (psp removed in Kubernetes 1.25)
          pspEnable: false

          ## Settings for whether to disable the drivers or other daemons if they are not needed
          csi:
            enableRbdDriver: true
            enableCephfsDriver: true
            enableGrpcMetrics: false
            # Set to true to enable host networking for CSI CephFS and RBD nodeplugins. This may be necessary
            # in some network configurations where the SDN does not provide access to an external cluster or
            # there is significant drop in read/write performance.
            enableCSIHostNetwork: true
            # set to false to disable deployment of snapshotter container in CephFS provisioner pod.
            enableCephfsSnapshotter: true
            # set to false to disable deployment of snapshotter container in NFS provisioner pod.
            enableNFSSnapshotter: false
            # set to false to disable deployment of snapshotter container in RBD provisioner pod.
            enableRBDSnapshotter: true
            # set to false if the selinux is not enabled or unavailable in cluster nodes.
            enablePluginSelinuxHostMount: false
            # set to true to enable Ceph CSI pvc encryption support.
            enableCSIEncryption: false

            # (Optional) set user created priorityclassName for csi plugin pods.
            pluginPriorityClassName: system-node-critical

            # (Optional) set user created priorityclassName for csi provisioner pods.
            provisionerPriorityClassName: system-cluster-critical

            # (Optional) policy for modifying a volume's ownership or permissions when the RBD PVC is being mounted.
            # supported values are documented at https://kubernetes-csi.github.io/docs/support-fsgroup.html
            rbdFSGroupPolicy: "File"

            # (Optional) policy for modifying a volume's ownership or permissions when the CephFS PVC is being mounted.
            # supported values are documented at https://kubernetes-csi.github.io/docs/support-fsgroup.html
            cephFSFSGroupPolicy: "File"

            # (Optional) policy for modifying a volume's ownership or permissions when the NFS PVC is being mounted.
            # supported values are documented at https://kubernetes-csi.github.io/docs/support-fsgroup.html
            nfsFSGroupPolicy: "File"

            # OMAP generator generates the omap mapping between the PV name and the RBD image
            # which helps CSI to identify the rbd images for CSI operations.
            # CSI_ENABLE_OMAP_GENERATOR need to be enabled when we are using rbd mirroring feature.
            # By default OMAP generator is disabled and when enabled it will be deployed as a
            # sidecar with CSI provisioner pod, to enable set it to true.
            enableOMAPGenerator: false

            # (Optional) set to true to enable adding volume metadata on the CephFS subvolumes and RBD images.
            # Not all users might be interested in getting volume/snapshot details as metadata on CephFS subvolume and RBD images.
            # Hence enable metadata is false by default.
            enableMetadata: false

            # Set replicas for csi provisioner deployment.
            provisionerReplicas: 2

            # The CSI GRPC timeout value (in seconds). It should be >= 120. If this variable is not set or is an invalid value, it's default to 150.
            grpcTimeoutInSeconds: 150

            # Allow starting unsupported ceph-csi image
            allowUnsupportedVersion: false

            # CEPH CSI RBD provisioner resource requirement list, Put here list of resource
            # requests and limits you want to apply for provisioner pod
            # csi-omap-generator resources will be applied only if enableOMAPGenerator is set to true
            csiRBDProvisionerResource: |
              - name : csi-provisioner
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-resizer
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-attacher
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-snapshotter
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-rbdplugin
                resource:
                  requests:
                    memory: 256Mi
                    cpu: 125m
                  limits:
                    memory: 1Gi
                    cpu: 500m
              - name : csi-omap-generator
                resource:
                  requests:
                    memory: 256Mi
                    cpu: 150m
                  limits:
                    memory: 1Gi
                    cpu: 500m
              - name : liveness-prometheus
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
            # CEPH CSI RBD plugin resource requirement list, Put here list of resource
            # requests and limits you want to apply for plugin pod
            csiRBDPluginResource: |
              - name : driver-registrar
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
              - name : csi-rbdplugin
                resource:
                  requests:
                    memory: 256Mi
                    cpu: 125m
                  limits:
                    memory: 1Gi
                    cpu: 500m
              - name : liveness-prometheus
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
            # CEPH CSI CephFS provisioner resource requirement list, Put here list of resource
            # requests and limits you want to apply for provisioner pod
            csiCephFSProvisionerResource: |
              - name : csi-provisioner
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-resizer
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-attacher
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-snapshotter
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-cephfsplugin
                resource:
                  requests:
                    memory: 356Mi
                    cpu: 125m
                  limits:
                    memory: 1Gi
                    cpu: 500m
              - name : liveness-prometheus
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
            # CEPH CSI CephFS plugin resource requirement list, Put here list of resource
            # requests and limits you want to apply for plugin pod
            csiCephFSPluginResource: |
              - name : driver-registrar
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
              - name : csi-cephfsplugin
                resource:
                  requests:
                    memory: 256Mi
                    cpu: 125m
                  limits:
                    memory: 1Gi
                    cpu: 500m
              - name : liveness-prometheus
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
            # CEPH CSI NFS provisioner resource requirement list, Put here list of resource
            # requests and limits you want to apply for provisioner pod
            csiNFSProvisionerResource: |
              - name : csi-provisioner
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 200m
              - name : csi-nfsplugin
                resource:
                  requests:
                    memory: 256Mi
                    cpu: 125m
                  limits:
                    memory: 1Gi
                    cpu: 500m
            # CEPH CSI NFS plugin resource requirement list, Put here list of resource
            # requests and limits you want to apply for plugin pod
            csiNFSPluginResource: |
              - name : driver-registrar
                resource:
                  requests:
                    memory: 128Mi
                    cpu: 50m
                  limits:
                    memory: 256Mi
                    cpu: 100m
              - name : csi-nfsplugin
                resource:
                  requests:
                    memory: 256Mi
                    cpu: 125m
                  limits:
                    memory: 1Gi
                    cpu: 500m
            # Enable the CSIAddons sidecar.
            csiAddons:
              enabled: false
              #image: "quay.io/csiaddons/k8s-sidecar:v0.5.0"
            # Enable the nfs csi driver.
            nfs:
              enabled: false
            # Enable topology based provisioning.
            topology:
              enabled: false
              # domainLabels define which node labels to use as domains
              # for CSI nodeplugins to advertise their domains
              # NOTE: the value here serves as an example and needs to be
              # updated with node labels that define domains of interest
              # domainLabels:
              # - kubernetes.io/hostname
              # - topology.kubernetes.io/zone
              # - topology.rook.io/rack
              
          enableDiscoveryDaemon: false
          cephCommandsTimeoutSeconds: "15"

          disableAdmissionController: false

          # Writing to the hostPath is required for the Ceph mon and osd pods. Given the restricted permissions in OpenShift with SELinux,
          # the pod must be running privileged in order to write to the hostPath volume, this must be set to true then.
          hostpathRequiresPrivileged: false

          # Disable automatic orchestration when new devices are discovered.
          disableDeviceHotplug: false

          # Blacklist certain disks according to the regex provided.
          discoverDaemonUdev:

          # imagePullSecrets option allow to pull docker images from private docker registry. Option will be passed to all service accounts.
          # imagePullSecrets:
          # - name: my-registry-secret

          # Whether the OBC provisioner should watch on the operator namespace or not, if not the namespace of the cluster will be used
          enableOBCWatchOperatorNamespace: true

          admissionController:
            # Set tolerations and nodeAffinity for admission controller pod.
            # The admission controller would be best to start on the same nodes as other ceph daemons.
            # tolerations:
            #    - key: key
            #      operator: Exists
            #      effect: NoSchedule
            # nodeAffinity: key1=value1,value2; key2=value3

          monitoring:
            # requires Prometheus to be pre-installed
            # enabling will also create RBAC rules to allow Operator to create ServiceMonitors
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
