---
prometheus_operator:
  # Define the Repo URL to download from:
  repo_url: "https://prometheus-community.github.io/helm-charts"
  repo_chart_ref: "prometheus-community/kube-prometheus-stack"

  prometheus:
    dashboard_users: "{{PROMETHEUS_DASHBOARD_USERS}}"

  alertmanager:
    dashboard_users: "{{ALERTMANAGER_DASHBOARD_USERS}}"