---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: mosquitto
  labels:
    app: mosquitto
data:
  passwd.txt: |
    <username1>:<encoded-password-here>
    <username2>:<encoded-password-here>
    <username3>:<encoded-password-here>