---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-config.yaml
  - configmap-passwd.yaml
  - longhorn-pvc.yaml
  - statefulset.yaml
  - service.yaml
