---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
