---
#
# Cert Manager, is a native certificate management controller for Kubernetes.  It is used as it
# stores everything as secrets instead of as files (as native Traefik will)
#

###[ Install Cert Manager ]########################################################################
- name: Install Cert Manager to Kubernetes Block
  block:

  - name: Install Cert Manager from Helm Chart
    kubernetes.core.helm:
      name: cert-manager
      create_namespace: yes
      release_namespace: "{{cert_manager.namespace}}"
      release_state: present
      chart_ref: "cert-manager"
      chart_repo_url: "{{cert_manager.helm_chart_url}}"
      chart_version: "{{install.cert_manager.install_version}}"
      wait: yes
      wait_timeout: 5m

  tags:
    - install_cert_manager