---
- name: Get Node Token and Add to Facts Block
  block:
  - name: Gather Node Token
    command: "cat /var/lib/rancher/k3s/server/node-token"
    register: node_token_output

  - name: Clean and add node_token to facts
    set_fact:
      node_token: "{{ node_token_output.stdout_lines[0] }}"
  tags: ["always"]
    
- name: Include Var Files
  include_vars: "{{ item }}.yml"
  tags: ["always"]
  loop:
      - k3s
      - k3s_traefik_api_secrets
      - containerd
      - helm
      - cert_manager

- name: Include Task Files
  include_tasks: "{{task_names}}.yml"
  tags: ["always"]
  loop:
    - 01_install_k3s
    - 02_install_containerd
    - 03_validate_k3s
    - 04_install_helm_client
    - 05_install_cert_manager
#    - 05_config_traefik_dns_certs
#    - 05_install_democratric-csi

  loop_control:
    loop_var: task_names
