---
- name: Check if node-token file exists
  stat:
    path: /var/lib/rancher/k3s/server/node-token
  register: node_token_file
  tags: ["always"]
  
- name: Get Node Token and Add to Facts Block
  block:
  - name: Gather Node Token
    slurp:
      path: "/var/lib/rancher/k3s/server/node-token"
    register: node_token_output
    when: node_token_file.stat.exists == true

  - name: Clean and add node_token to facts
    set_fact:
      node_token: "{{ node_token_output.content | b64decode | regex_replace('\n', '')}}"
    when: node_token_file.stat.exists == true
  tags: ["always"]
  
- name: Include Var Files
  include_vars: "{{ item }}.yml"
  tags: ["always"]
  loop:
      - k3s
      - k3s_traefik_api_secrets
      - containerd
      - helm
      - cert_manager

- name: Include Task Files
  include_tasks: "{{task_names}}.yml"
  tags: ["always"]
  loop:
    - 01_install_k3s
    - 02_install_containerd
    - 03_validate_k3s
    - 04_install_helm_client
    - 05_install_cert_manager
    - 06_config_traefik_dns_certs
#    - 07_install_democratric-csi

  loop_control:
    loop_var: task_names
