---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
  # - servicemonitor.yaml

# Grafana Dashboard if Service Monitor and Metrics are Enabled:
# configMapGenerator:
#   - name: gitea-dashboard-17802
#     files: [ gitea-dashboard-17802.json ]

# generatorOptions:
#   disableNameSuffixHash: true
#   labels:
#     grafana_dashboard: "true"
