---
resources:
  - prometheus-self-alerts.yaml
  - argocd-prometheus-alerts.yaml
  - longhorn-prometheus-alerts.yaml
  - node-prometheus-alerts.yaml
  - traefik-prometheus-alerts.yaml
  - cert-manager-prometheus-alerts.yaml
  - sealed-secrets-prometheus-alerts.yaml
  - node-zfs-alerts.yaml
  - pod-prometheus-alerts.yaml
  - mosquitto-prometheus-alerts.yaml
