---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: node-zfs-alerts                                 
  namespace: monitoring
spec:
  groups:
    - name: node-zfs-alerts                                     # Name of the prometheus rule group
      rules:
        - alert: ZFSPoolUnexpectedState
          expr: 'zfs_pool_health > 0'
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: ZFS pool issue on (instance {{ $labels.instance }})
            description: |
              A ZFS zpool "{{ $labels.pool }}" on "{{ $labels.instance }}" is in a unexpected state, code: "{{ $value }}".
              Health status codes [0: ONLINE, 1: DEGRADED, 2: FAULTED, 3: OFFLINE, 4: UNAVAIL, 5: REMOVED, 6: SUSPENDED].
