---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: mosquitto-mqtt
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"  # Lower the number the sooner to deploy
spec:
  project: default

  source:
    repoURL:  https://github.com/<USER_NAME>/<REPO_NAME>.git
    targetRevision: HEAD
    path: workloads/mosquitto
  destination:
    server:  https://kubernetes.default.svc
    namespace: mosquitto

  # Allow changes to number of replicas
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
      - /spec/replicas

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    -  Validate=true
