---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# NOTES: ConfigMaps need "subPath" mounting, unable to get working with ConfigMapGenerator
# 1) Review base/application/configmap-config.yaml for mosquitto.conf file
# 2) Review base/application/configmap-passwd.yaml for user / password file.

# As user / password file data is already encoded, it was not made a Kubernetes secret.

bases:
  - ./base/application/

images:
  - name: eclipse-mosquitto
    newTag: 2.0.14

# Set Service to LoadBalancer and Specify IP Address to use
patches:
  - patch: |-
      - op: add
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerIP
        value: 192.168.10.241
    target:
      kind: Service

commonLabels:
  app: mosquitto
  app.kubernetes.io/instance: mosquitto
  app.kubernetes.io/name: mosquitto